version: "3.9"
services:
  backend:
    volumes:
      - ./backend/.:/app
    build:
      dockerfile: Dockerfile.devel
  frontend:
    volumes:
      - ./frontend/.:/app
    build:
      dockerfile: Dockerfile.devel